// frontend/portal-store/components/marketing/newsletter-modal.tsx
'use client'

import { useState, useEffect } from 'react'
import { X } from 'lucide-react'

export function NewsletterModal() {
  const [open, setOpen] = useState(false)
  const [email, setEmail] = useState('')
  const [done, setDone] = useState(false)

  useEffect(() => {
    if (sessionStorage.getItem('dreamy_newsletter_seen')) return
    const t = setTimeout(() => setOpen(true), 4000)
    return () => clearTimeout(t)
  }, [])

  const close = () => {
    setOpen(false)
    sessionStorage.setItem('dreamy_newsletter_seen', '1')
  }

  if (!open) return null

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-ink/50 backdrop-blur-sm" onClick={close} />
      <div className="relative grid w-full max-w-3xl animate-fadeup overflow-hidden rounded-sm bg-canvas shadow-lift sm:grid-cols-2">
        <button onClick={close} className="absolute right-3 top-3 z-10 cursor-pointer rounded-full bg-canvas/80 p-1.5" aria-label="Close"><X className="h-4 w-4" /></button>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src="/competitor-refs/davidsbridal/wedding-dress-04.jpg" alt="Outdoor bride" className="hidden h-full w-full object-cover sm:block" />
        <div className="flex flex-col justify-center p-8 sm:p-10">
          <p className="eyebrow mb-2">Welcome to Dreamy</p>
          <h2 className="font-display text-3xl font-medium leading-tight">Take 10% off<br />your first order</h2>
          <p className="mt-3 text-sm text-ink-soft">Join our list for outdoor wedding inspiration, early access, and a little something to start your story.</p>
          {done ? (
            <p className="mt-6 rounded-sm bg-sage/15 px-4 py-3 text-sm text-sage-deep">Welcome! Check your inbox for your code.</p>
          ) : (
            <form onSubmit={(e) => { e.preventDefault(); setDone(true) }} className="mt-6 space-y-3">
              <label htmlFor="modal-email" className="sr-only">Email</label>
              <input id="modal-email" type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Your email address" className="w-full rounded-sm border border-line bg-surface px-4 py-3 text-sm outline-none focus:border-gold" />
              <button type="submit" className="btn-primary w-full">Reveal My Code</button>
            </form>
          )}
          <button onClick={close} className="mt-3 cursor-pointer text-xs text-ink-faint underline">No thanks, I’ll pay full price</button>
        </div>
      </div>
    </div>
  )
}

// hhspec/prototype/src/components/NewsletterModal.vue
<script setup>
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { TransitionRoot, TransitionChild, Dialog, DialogPanel } from '@headlessui/vue'
import { useUiStore } from '../stores/ui'
import { PRODUCT_IMAGES } from '../data/catalog'

const ui = useUiStore()
const { t } = useI18n()
const email = ref('')
const done = ref(false)

function submit() {
  if (!email.value) return
  done.value = true
  ui.pushToast(t('newsletter.success'))
  setTimeout(() => ui.closeNewsletter(), 1400)
}
</script>

<template>
  <TransitionRoot :show="ui.newsletterOpen" as="template">
    <Dialog @close="ui.closeNewsletter()" class="relative z-[60]">
      <TransitionChild as="template" enter="duration-300 ease-out" enter-from="opacity-0" enter-to="opacity-100" leave="duration-200 ease-in" leave-from="opacity-100" leave-to="opacity-0">
        <div class="fixed inset-0 bg-ink-950/60 backdrop-blur-sm" />
      </TransitionChild>
      <div class="fixed inset-0 flex items-center justify-center p-4">
        <TransitionChild as="template" enter="duration-400 ease-editorial" enter-from="opacity-0 scale-95" enter-to="opacity-100 scale-100" leave="duration-200 ease-in" leave-from="opacity-100" leave-to="opacity-0 scale-95">
          <DialogPanel class="w-full max-w-3xl bg-white grid sm:grid-cols-2 overflow-hidden shadow-2xl">
            <div class="hidden sm:block relative">
              <img :src="PRODUCT_IMAGES[12]" alt="Maison Eden" class="absolute inset-0 w-full h-full object-cover" />
            </div>
            <div class="p-8 sm:p-10 relative">
              <button @click="ui.closeNewsletter()" class="absolute top-4 right-4 text-ink-400 hover:text-ink-950" aria-label="Close"><svg class="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path stroke-linecap="round" d="M6 6l12 12M6 18L18 6" /></svg></button>
              <p class="editorial-label text-champagne-600 mb-3">Maison Eden</p>
              <h2 class="font-serif text-3xl leading-tight mb-3">{{ t('newsletter.title') }}</h2>
              <p class="text-sm text-ink-500 mb-6">{{ t('newsletter.desc') }}</p>
              <form @submit.prevent="submit" class="space-y-3">
                <input v-model="email" type="email" required placeholder="Email address" class="field" />
                <button type="submit" class="btn-ink w-full">{{ t('newsletter.cta') }}</button>
              </form>
              <button class="editorial-label text-ink-400 hover:text-ink-950 mt-4" @click="ui.closeNewsletter()">{{ t('newsletter.noThanks') }}</button>
            </div>
          </DialogPanel>
        </TransitionChild>
      </div>
    </Dialog>
  </TransitionRoot>
</template>
