// frontend/portal-store/components/product/product-card.tsx
'use client'

/**
 * ProductCard（COMP-CAT-S01，layout-keep + data-swap）：
 * props 由 mock Product 切换为 StoreProductCard（imageUrl/swatches/ratingAvg/ratingCount/isNew/isBest/compareAt）。
 * 视觉结构不变；收藏未登录 → 引导 /account/login（决策 18）。
 */

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { Heart } from 'lucide-react'
import type { StoreProductCard } from '@/lib/api/store-types'
import { useStore } from '@/components/store-provider'
import { formatPrice, installments, cn } from '@/lib/utils'
import { Badge, Stars } from '@/components/ui/primitives'

export function badgeOf(product: StoreProductCard): { label: string; variant: 'default' | 'sale' | 'new' } | null {
  if (product.compareAt && product.compareAt > product.price) return { label: 'Sale', variant: 'sale' }
  if (product.isNew) return { label: 'New', variant: 'new' }
  if (product.isBest) return { label: 'Best Seller', variant: 'default' }
  return null
}

export function ProductCard({ product, onQuickView }: { product: StoreProductCard; onQuickView?: (p: StoreProductCard) => void }) {
  const router = useRouter()
  const { currency, toggleWishlist, isWished } = useStore()
  const wished = isWished(product.id)
  const badge = badgeOf(product)
  const rating = product.ratingAvg ?? 0
  const swatches = product.swatches ?? []

  const onWish = async () => {
    const ok = await toggleWishlist(product.id)
    if (!ok) router.push(`/account/login?returnTo=/product/${product.slug}`)
  }

  return (
    <div className="group relative">
      <Link href={`/product/${product.slug}`} className="block">
        <div className="relative aspect-[3/4] overflow-hidden rounded-sm bg-muted">
          {product.imageUrl && (
            // eslint-disable-next-line @next/next/no-img-element
            <img src={product.imageUrl} alt={product.name} className="absolute inset-0 h-full w-full object-cover transition-transform duration-700 ease-luxe group-hover:scale-105" />
          )}
          {badge && (
            <div className="absolute left-3 top-3">
              <Badge variant={badge.variant}>{badge.label}</Badge>
            </div>
          )}
          {onQuickView && (
            <button
              onClick={(e) => { e.preventDefault(); onQuickView(product) }}
              className="absolute inset-x-3 bottom-3 cursor-pointer rounded-sm bg-canvas/95 py-2.5 text-[11px] font-medium uppercase tracking-luxe text-ink opacity-0 shadow-soft backdrop-blur transition-all duration-300 group-hover:translate-y-0 group-hover:opacity-100"
            >
              Quick View
            </button>
          )}
        </div>
      </Link>
      <button
        onClick={onWish}
        className="absolute right-3 top-3 cursor-pointer rounded-full bg-canvas/90 p-2 shadow-soft backdrop-blur transition-colors hover:bg-canvas"
        aria-label={wished ? 'Remove from wishlist' : 'Add to wishlist'}
      >
        <Heart className={cn('h-4 w-4 transition-colors', wished ? 'fill-blush text-blush' : 'text-ink')} />
      </button>

      <div className="mt-3.5">
        <div className="flex items-start justify-between gap-2">
          <Link href={`/product/${product.slug}`} className="text-sm font-medium leading-snug transition-colors hover:text-gold-deep">{product.name}</Link>
        </div>
        {(product.ratingCount ?? 0) > 0 && (
          <div className="mt-1 flex items-center gap-2">
            <Stars rating={rating} />
            <span className="text-xs text-ink-faint">({product.ratingCount})</span>
          </div>
        )}
        <div className="mt-1.5 flex items-center gap-2">
          <span className="text-sm font-medium text-ink">{formatPrice(product.price, currency, product.multiCurrencyPrices)}</span>
          {product.compareAt && product.compareAt > product.price && (
            <span className="text-sm text-ink-faint line-through">{formatPrice(product.compareAt, currency)}</span>
          )}
        </div>
        {product.installment !== false && (
          <p className="mt-0.5 text-[11px] text-ink-faint">or 4× {formatPrice(Number(installments(product.price)), currency)} with Klarna</p>
        )}
        {swatches.length > 1 && (
          <div className="mt-2 flex items-center gap-1.5">
            {swatches.slice(0, 5).map((c, i) => (
              c.url ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img key={`${c.colorName}-${i}`} src={c.url} alt={c.colorName ?? ''} title={c.colorName} className="h-3.5 w-3.5 rounded-full border border-line object-cover" />
              ) : (
                <span key={`${c.colorName}-${i}`} className="h-3.5 w-3.5 rounded-full border border-line bg-muted" title={c.colorName} />
              )
            ))}
            {swatches.length > 5 && <span className="text-[10px] text-ink-faint">+{swatches.length - 5}</span>}
          </div>
        )}
      </div>
    </div>
  )
}

/** ProductRef（内容关联商品）→ 卡片 props 子集映射（COMP-MKT-S03/S06 复用） */
export function productRefToCard(ref: { id: number; slug: string; name: string; price: number; imageUrl?: string }): StoreProductCard {
  return { id: ref.id, slug: ref.slug, name: ref.name, price: ref.price, imageUrl: ref.imageUrl, installment: false }
}

/** ProductBrief（购物车/收藏/浏览历史）→ 卡片 props 映射 */
export function productBriefToCard(brief: {
  id: number
  slug: string
  name: string
  price: number
  compareAt?: number | null
  multiCurrencyPrices?: Record<string, number> | null
  imageUrl?: string
}): StoreProductCard {
  return {
    id: brief.id,
    slug: brief.slug,
    name: brief.name,
    price: brief.price,
    compareAt: brief.compareAt,
    multiCurrencyPrices: brief.multiCurrencyPrices,
    imageUrl: brief.imageUrl
  }
}

// hhspec/prototype/src/components/ProductCard.vue
<script setup>
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useCurrencyStore } from '../stores/currency'
import { useWishlistStore } from '../stores/wishlist'
import { useUiStore } from '../stores/ui'
import ColorSwatches from './ColorSwatches.vue'

const props = defineProps({
  product: { type: Object, required: true },
  showRating: { type: Boolean, default: false },
})

const router = useRouter()
const currency = useCurrencyStore()
const wishlist = useWishlistStore()
const ui = useUiStore()

const hovered = ref(false)
const activeColor = ref(props.product.colorIds?.[0] || '')

const displayImg = computed(() => (hovered.value ? props.product.hoverImg : props.product.thumb))
const saved = computed(() => wishlist.has(props.product.id))

const tag = computed(() => {
  const t = props.product.tags || []
  if (t.includes('new')) return { key: 'new', label: 'New' }
  if (t.includes('best-seller')) return { key: 'best', label: 'Best Seller' }
  return null
})

function go() {
  router.push(`/products/${props.product.slug}`)
}
function toggleWish() {
  const added = wishlist.toggle(props.product.id)
  ui.pushToast(added ? 'Saved to wishlist' : 'Removed from wishlist', added ? 'success' : 'muted')
}
function quickView() {
  ui.openQuickView(props.product)
}
</script>

<template>
  <div class="group relative">
    <!-- image -->
    <div
      class="relative overflow-hidden bg-ink-50 aspect-[3/4] cursor-pointer"
      @mouseenter="hovered = true"
      @mouseleave="hovered = false"
      @click="go"
    >
      <img
        :src="displayImg"
        :alt="product.fullName"
        loading="lazy"
        class="absolute inset-0 w-full h-full object-cover transition-all duration-700 ease-editorial group-hover:scale-[1.04]"
      />

      <!-- tags -->
      <div class="absolute top-3 left-3 flex flex-col gap-1.5">
        <span v-if="tag" class="bg-ink-950 text-white editorial-label-light px-2.5 py-1 text-[10px]">{{ tag.label }}</span>
        <span v-if="product.shipsNow" class="bg-white text-ink-900 editorial-label px-2.5 py-1 text-[10px] text-ink-700">Ships Now</span>
      </div>

      <!-- wishlist -->
      <button
        type="button"
        @click.stop="toggleWish"
        :aria-label="saved ? 'Remove from wishlist' : 'Add to wishlist'"
        class="absolute top-3 right-3 w-9 h-9 grid place-items-center bg-white/85 backdrop-blur-sm transition-all duration-200 hover:bg-white"
      >
        <svg class="w-4 h-4" :class="saved ? 'fill-champagne-500 stroke-champagne-500' : 'fill-none stroke-ink-700'" viewBox="0 0 24 24" stroke-width="1.5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
        </svg>
      </button>

      <!-- quick view -->
      <button
        type="button"
        @click.stop="quickView"
        class="absolute bottom-0 inset-x-0 bg-ink-950/92 text-white py-3 editorial-label-light text-[11px] translate-y-full group-hover:translate-y-0 transition-transform duration-300 ease-editorial"
      >
        Quick View
      </button>
    </div>

    <!-- meta -->
    <div class="pt-4 space-y-2">
      <div class="flex items-start justify-between gap-3">
        <h3 class="font-serif text-lg leading-tight text-ink-950 cursor-pointer hover:text-champagne-700 transition-colors" @click="go">
          {{ product.name }}
        </h3>
      </div>
      <p class="editorial-label text-ink-400 text-[10px]">{{ product.silhouette }} · {{ product.fabric }}</p>
      <StarRating v-if="showRating" :rating="product.rating" :count="product.reviewCount" />
      <div class="flex items-baseline gap-2">
        <span class="text-sm text-ink-900 tabular-nums">{{ currency.format(product.basePrice) }}</span>
        <span v-if="product.originalPrice" class="text-xs text-ink-400 line-through tabular-nums">{{ currency.format(product.originalPrice) }}</span>
      </div>
      <ColorSwatches v-if="product.colorIds?.length" v-model="activeColor" :color-ids="product.colorIds" :max="6" />
    </div>
  </div>
</template>
